### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by Gandalf-** [robertfoss/audio_shop#3]
Hey! 

Going through your script there are two undefined variables, both on line 159. Shellcheck caught them too, and the descriptions are given below. I couldn't tell what these are supposed to be assigned to, but you probably do!

 1 mangle.sh|159 col 10 warning| streams_stream_0_width is referenced but not assigned. [SC2154]
 2 mangle.sh|159 col 39 warning| streams_stream_0_height is referenced but not assigned. [SC2154]

**Comment by Hagmar** [comment]
The output of `cmd ffprobe -v error -of flat=s=_ -select_streams v:0 -show_entries stream=height,width $1` on [line 158](https://github.com/robertfoss/audio_shop/blob/01f03b6c8355f91394c1fde651d50203602a30e3/mangle.sh#L158) is

streams_stream_0_width=_width_  
streams_stream_0_height=_height_

which then gets eval'ed in order to set the variables, so they won't be undefined when they are used :)

**Comment by robertfoss** [comment]
Thanks @Hagmar, that's exactly what's going on.
